version: '3.3'
services:
  redis:
    image: redis
    container_name: mp-redis
    networks:
      - moviepilot    
    restart: always

  moviepilot:
    stdin_open: true
    tty: true
    container_name: moviepilot-v2
    hostname: moviepilot-v2
    networks:
      - moviepilot
    ports:
      - target: 4500
        published: 4500
        protocol: tcp
      - target: 4501
        published: 4501
        protocol: tcp
      - target: 9096
        published: 9096
        protocol: tcp
    volumes:
      - '/vol2/1000/Media:/media'
      - '/vol1/1000/Docker/MoviePilot/config:/config'
      - '/vol1/1000/Docker/MoviePilot/core:/moviepilot/.cache/ms-playwright'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    environment:
      - 'NGINX_PORT=4500'
      - 'PORT=4501'
      - 'PUID=0'
      - 'PGID=0'
      - 'UMASK=000'
      - 'TZ=Asia/Shanghai'
      - 'MOVIEPILOT_AUTO_UPDATE=release'
      - 'PROXY_HOST=http://192.168.2.2:8888'
      - 'BIG_MEMORY=true'
      - 'CACHE_BACKEND_TYPE=redis'
      - 'CACHE_BACKEND_URL=redis://redis'
      - 'CACHE_REDIS_MAXMEMORY=0'
      - 'SUPERUSER=admin' 
    restart: always
    image: jxxghp/moviepilot-v2:latest
    depends_on:
      - redis

  emby:
    image: emby/embyserver
    container_name: embyserver
    networks:
      - moviepilot
    environment:
      - UID=1000
      - GID=100
      - GIDLIST=100
      - TZ=Asia/Shanghai
      - HTTPS_PROXY=http://192.168.2.2:8888
      - HTTP_PROXY=http://192.168.2.2:8888      
    volumes:
      - /vol1/1000/Docker/Emby:/config
      - /vol2/1000/Media:/media
    ports:
      - 8096:8096
      - 8920:8920

    restart: always

  qbittorrent:
    image: linuxserver/qbittorrent:4.6.4
    container_name: qbittorrent
    networks:
      - moviepilot
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=000
      - TZ=Asia/Shanghai
      - WEBUI_PORT=8989
    volumes:
      - /vol1/1000/Docker/qBittorrent/config:/config
      - /vol2/1000/Media:/downloads
    ports:
      - 8989:8989
      - 11451:11451
      - 11451:11451/udp
    restart: always

networks:
  moviepilot:
    name: moviepilot
